### ISSUE TITLE
Windows only, due to some software altering path var not ending in ;

### ISSUE THREAD

**Issue by ivanwel** [eyedouble/erlsass#3]
Erlsass appends folder with binaries to Windows Path var.
Due to some software altering path var but not ending it with ; Erlsass appends inproperly.

{error,{load_failed,"Failed to load NIF library .../_build/default/lib/erlsass/priv/erlsass_nif: 'The specified module could not be found.'"}}

**Comment by Spoowy** [comment]
Could you resolve this issue?
